
name: Build & Test

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: pinn:fisher
      - name: Run tests
        run: docker run --rm pinn:fisher pytest -q
